"""Detailed work descriptions for every Epic, Task and Sub-task of the IMS plan.

DETAILS[wbs_id] = (goal, steps, deliverable, done_criteria, depends_on, references)
EPIC_DETAILS[group_id] = (scope, exit_criteria)
Kept apart from ims_data.py so the schedule stays readable; keys must match WBS ids.
"""

EPIC_DETAILS = {
    "1": ("Lập kế hoạch, theo dõi và kiểm soát toàn bộ dự án theo PMBOK: phạm vi, lịch, chi phí, rủi ro, truyền thông.",
          ["Charter, Scope, WBS, Gantt, Risk Register được duyệt ở M1",
           "Status Report nộp đủ 12 tuần, Burndown mỗi Sprint được lưu",
           "Báo cáo tổng kết và lessons learned hoàn thành trước 20/11/2026"]),
    "2": ("Thu thập, đặc tả và quản lý yêu cầu: SRS, Use Case, User Story, RTM; giữ yêu cầu đồng bộ suốt dự án.",
          ["SRS có 30 FR, 10 NFR, 15 BR được duyệt",
           "16 User Story có AC kiểm thử được",
           "RTM phủ 100% FR tới User Story và Test Case"]),
    "3": ("Thiết kế giao diện, kiến trúc, cơ sở dữ liệu và API làm baseline cho phát triển.",
          ["Wireframe các màn hình chính, ERD 12 bảng, OpenAPI 36 endpoint",
           "Design Baseline được ký duyệt ở mốc M1"]),
    "4": ("Chuẩn bị môi trường phát triển, quản lý mã nguồn, CI và công cụ quản lý dự án.",
          ["Repo GitHub có main/develop được bảo vệ",
           "docker compose up chạy được MySQL + backend + frontend",
           "GitHub Actions chạy build và test cho mỗi PR"]),
    "5": ("Sprint 1: đăng nhập JWT, phân quyền 3 role, quản lý tài khoản và phòng ban (US-01..US-04, 13 SP).",
          ["US-01..US-04 Done theo Definition of Done",
           "Test case AUTH, RBAC, USR, DEP đạt; đạt mốc M2 ngày 25/09/2026"]),
    "6": ("Sprint 2: đăng ký thực tập, duyệt hồ sơ, quản lý Intern, quản lý và phân công Mentor (US-05..US-08, 14 SP).",
          ["US-05..US-08 Done", "Test case REG, APR, INT, MEN đạt; đạt mốc M3 ngày 09/10/2026"]),
    "7": ("Sprint 3: giao và theo dõi task, chấm công, báo cáo tuần (US-09..US-12, 16 SP).",
          ["US-09..US-12 Done", "Test case TASK, ATT, RPT đạt; đạt mốc M4 ngày 23/10/2026"]),
    "8": ("Sprint 4: đánh giá Intern, theo dõi tiến độ, dashboard, xuất kết quả cuối kỳ (US-13..US-16, 16 SP).",
          ["US-13..US-16 Done, đủ 30 FR (Feature Complete)",
           "Test case EVA, PRG, DSH, EXP đạt; 8 kịch bản UAT sẵn sàng; mốc M5 ngày 06/11/2026"]),
    "9": ("Đảm bảo chất lượng xuyên suốt: Test Plan, test case, kiểm thử tự động, quản lý bug, hồi quy.",
          ["40 test case được viết và chạy", "Postman/Newman và Selenium chạy được",
           "Tiêu chí kết thúc: 100% test Critical/High đạt, 0 bug S1/S2 mở"]),
    "10": ("Sprint 5: ổn định, sửa bug, UAT, phát hành v1.0.0 và nghiệm thu.",
           ["0 bug S1/S2, UAT Sign-off 8/8 kịch bản", "Tag v1.0.0, đủ tài liệu bàn giao, demo nghiệm thu ngày 20/11/2026"]),
}

DETAILS = {
    # ---------------------------------------------------------------- 1 PM
    "1.1": ("Chính thức khởi động dự án và thống nhất mục tiêu với giảng viên.",
            ["Viết mục đích, mục tiêu SMART, phạm vi tổng quát", "Lập danh sách stakeholder và mức ảnh hưởng",
             "Định nghĩa 6 tiêu chí thành công SC-01..SC-06", "Ghi giả định, ràng buộc, rủi ro chính, ngân sách quy đổi"],
            "Project Charter (Word/PDF) trong docs/pm/", ["Có đủ 12 mục của Charter", "Giảng viên xác nhận qua email"],
            [], "Chương 2 báo cáo"),
    "1.2": ("Chốt ranh giới phạm vi để làm căn cứ kiểm soát thay đổi.",
            ["Liệt kê in-scope theo FR-01..FR-30", "Liệt kê out-of-scope (lương, HRM, mobile, SSO...)",
             "Ghi tiêu chí chấp nhận sản phẩm"],
            "Scope Statement", ["Mọi FR được xếp in-scope hoặc out-of-scope", "Được duyệt cùng Charter"],
            ["1.1"], "Mục 1.3 báo cáo"),
    "1.3": ("Phân rã toàn bộ công việc thành gói nhỏ có thể ước lượng và giao việc.",
            ["Chia 11 nhóm WBS theo nguyên tắc 100%", "Tách mỗi gói thành việc 1-3 ngày, 1 vai trò chịu trách nhiệm",
             "Ước lượng Story Point bằng Planning Poker và giờ công từ dưới lên"],
            "Bảng WBS + ước lượng (Excel)", ["Không việc nào > 3 ngày trừ việc lặp theo Sprint", "Tổng giờ và SP khớp báo cáo"],
            ["1.2"], "Mục 6.3, 6.4 báo cáo"),
    "1.4": ("Lập lịch baseline và xác định đường găng.",
            ["Nhập WBS vào Gantt, xác định quan hệ phụ thuộc", "Tìm đường găng, đặt 6 mốc M1..M6",
             "Kiểm tra tải tuần, san tải nếu vượt năng lực"],
            "IMS_Gantt_Chart.xlsx (baseline)", ["Không tuần nào vượt năng lực", "Đường găng và mốc được đánh dấu"],
            ["1.3"], "IMS_Gantt_Chart.xlsx, mục 6.5"),
    "1.5": ("Lập kế hoạch nguồn lực cho mô hình 1 người kiêm 5 vai trò.",
            ["Xây lịch luân phiên vai trò theo khung giờ", "Lập ma trận RACI", "Tính năng lực giờ/tuần theo lịch học"],
            "Lịch đội mũ + RACI", ["Mỗi hoạt động có đúng 1 vai trò A", "Năng lực tuần được ghi rõ"],
            ["1.3"], "Chương 3 báo cáo"),
    "1.6": ("Dựng công cụ quản lý dự án trên Jira khớp với WBS.",
            ["Tạo space Scrum company-managed key IM", "Tạo 6 Sprint, bật Story Point, Time tracking",
             "Import backlog CSV, cấu hình board, quick filter theo vai trò"],
            "Jira space IMS có đủ Epic/Story/Task/Subtask", ["131 work item, Sprint 1-4 có 13/14/16/16 SP",
                                                            "Board có cột In Testing, WIP limit 2"],
            ["1.3", "1.4"], "Huong_dan_Jira_IMS.docx"),
    "1.7": ("Chuẩn bị các công cụ quản lý rủi ro, truyền thông và thay đổi.",
            ["Lập Risk Register R-01..R-12 có điểm xác suất x tác động", "Lập Communication Plan",
             "Soạn biểu mẫu Change Request"],
            "Risk Register, Communication Plan, mẫu CR", ["Mỗi rủi ro có biện pháp và chủ sở hữu", "Mẫu CR có mục đánh giá tác động"],
            ["1.1"], "Chương 7, mục 6.7, 6.10"),
    "1.8": ("Vận hành nhịp Scrum cho 5 Sprint.",
            ["Đầu Sprint: Sprint Planning, đặt Sprint Goal, Start sprint trên Jira",
             "Hằng ngày: ghi nhật ký 3 câu hỏi vào comment", "Cuối Sprint: Review (demo), Retrospective, Complete sprint"],
            "Biên bản Planning/Review/Retro mỗi Sprint", ["5 Sprint đều có đủ 3 biên bản", "Mỗi Retro có ít nhất 1 hành động cải tiến"],
            ["1.6"], "Mục 6.1 báo cáo"),
    "1.9": ("Đo và báo cáo tiến độ, chi phí mỗi tuần.",
            ["Log work giờ thực tế trên Jira", "Chụp Burndown/Velocity", "Tính PV, EV, AC, SPI, CPI",
             "Viết Weekly Status Report"],
            "12 Weekly Status Report", ["Báo cáo nộp trước Chủ nhật 23:59", "SPI/CPI < 0,95 có hành động khắc phục"],
            ["1.6"], "Chương 9 báo cáo"),
    "1.10": ("Đóng dự án và bàn giao hồ sơ.",
             ["Tổng hợp baseline và thực tế (lịch, chi phí, phạm vi)", "Viết lessons learned", "Đóng gói hồ sơ bàn giao"],
             "Báo cáo tổng kết", ["Đủ danh mục bàn giao ở chương 10", "Có so sánh baseline và thực tế"],
             ["10.8"], "Chương 10 báo cáo"),
    # ---------------------------------------------------------------- 2 BA
    "2.1": ("Hiểu quy trình quản lý thực tập hiện tại và nhu cầu 3 nhóm người dùng.",
            ["Soạn bộ câu hỏi phỏng vấn cho Admin, Mentor, Intern", "Phỏng vấn giả lập hoặc hỏi bạn đã đi thực tập",
             "Tổng hợp vấn đề hiện tại và mong muốn"],
            "Biên bản khảo sát", ["Có ít nhất 5 vấn đề và 10 nhu cầu được ghi nhận"], [], "Mục 1.1 báo cáo"),
    "2.2": ("Đặc tả đầy đủ yêu cầu chức năng.",
            ["Viết FR-01..FR-30 kèm actor", "Gắn mỗi FR với User Story dự kiến", "Rà soát trùng lặp, mâu thuẫn"],
            "SRS phần yêu cầu chức năng", ["30 FR có mã, mô tả, actor", "Mỗi FR kiểm thử được"],
            ["2.1"], "Bảng 4.2 báo cáo"),
    "2.3": ("Đặc tả yêu cầu chất lượng có thể đo được.",
            ["Viết NFR-01..NFR-10 về hiệu năng, bảo mật, khả dụng...", "Gắn ngưỡng đo cụ thể cho từng NFR"],
            "SRS phần phi chức năng", ["Mỗi NFR có con số hoặc tiêu chí kiểm tra"], ["2.2"], "Bảng 4.3 báo cáo"),
    "2.4": ("Ghi nhận các quy tắc nghiệp vụ ràng buộc hệ thống.",
            ["Viết BR-01..BR-15 cho đăng ký, phân Mentor, chấm công, báo cáo, đánh giá",
             "Kèm ví dụ minh họa cho BR có công thức (BR-11, BR-13)"],
            "Danh sách Business Rules", ["Mỗi BR được tham chiếu bởi ít nhất 1 AC hoặc test case"],
            ["2.2"], "Bảng 4.4 báo cáo"),
    "2.5": ("Mô hình hóa tương tác người dùng với hệ thống.",
            ["Vẽ Use Case Diagram 4 actor, 12 UC bằng draw.io", "Đặc tả luồng chính, luồng thay thế cho UC-04/05, UC-08, UC-11"],
            "Use Case Diagram + đặc tả", ["12 UC có trên sơ đồ", "3 UC chính có đặc tả đầy đủ"],
            ["2.2"], "Mục 4.5 báo cáo"),
    "2.6": ("Mô tả luồng nghiệp vụ và vòng đời đối tượng.",
            ["Vẽ Activity Diagram luồng thực tập từ đăng ký tới hoàn thành", "Vẽ State Diagram hồ sơ Intern và Task"],
            "Activity Diagram, 2 State Diagram", ["Trạng thái khớp enum trong ERD"], ["2.5"], "Mục 4.6 báo cáo"),
    "2.7": ("Chuyển yêu cầu thành Product Backlog cho Scrum.",
            ["Viết 16 User Story theo mẫu Là... tôi muốn... để...", "Viết 2-3 AC Given-When-Then mỗi Story",
             "Ước lượng SP, gán Sprint và độ ưu tiên"],
            "Product Backlog 16 Story", ["Mỗi Story đạt Definition of Ready", "Tổng 59 SP"],
            ["2.2", "2.4"], "Bảng 4.x Product Backlog"),
    "2.8": ("Đảm bảo truy vết yêu cầu tới thiết kế và kiểm thử.",
            ["Lập ma trận FR - User Story - API/UI - Test Case", "Đánh dấu FR chưa được phủ"],
            "RTM (Excel)", ["100% FR có Story và ít nhất 1 test case"], ["2.7"], "Bảng RTM chương 8"),
    "2.9": ("Giữ yêu cầu đồng bộ khi có thay đổi.",
            ["Mỗi khi CR được duyệt: cập nhật FR/BR/AC liên quan", "Cập nhật RTM và thông báo cho vai trò bị ảnh hưởng"],
            "RTM và AC phiên bản mới", ["Không có CR đã duyệt nào chưa cập nhật RTM"], ["2.8"], "Mục 6.10 báo cáo"),
    # ---------------------------------------------------------------- 3 design
    "3.1": ("Xác định cấu trúc điều hướng cho 3 role.",
            ["Liệt kê màn hình UI-01..UI-14 theo role", "Vẽ sitemap và luồng chuyển màn hình"],
            "Sitemap (draw.io)", ["Mỗi FR có màn hình thực hiện"], ["2.2"], "Bảng màn hình mục 5.4"),
    "3.2": ("Thiết kế bố cục các màn hình chính trước khi code.",
            ["Wireframe Login, Dashboard, Intern List/Detail, Task, Weekly Report, Evaluation trên Figma",
             "Thống nhất màu, font, component dùng chung"],
            "Link Figma wireframe", ["7 màn hình chính có wireframe", "BA xác nhận khớp AC"], ["3.1"], "UI-01..UI-14"),
    "3.3": ("Chốt kiến trúc kỹ thuật.",
            ["Chọn React SPA + Spring Boot REST, 3 lớp Controller-Service-Repository",
             "Quy định cấu trúc package, xử lý lỗi, bảo mật JWT"],
            "Tài liệu kiến trúc 1-2 trang", ["Có sơ đồ kiến trúc và bảng công nghệ"], ["2.3"], "Mục 5.1 báo cáo"),
    "3.4": ("Thiết kế cơ sở dữ liệu.",
            ["Vẽ ERD 12 bảng, khóa chính/ngoại", "Đặt UNIQUE (email, intern+ngày chấm công, intern+loại đánh giá)",
             "Thêm index cho cột lọc (status, department_id, mentor_id)"],
            "ERD + script V1__init.sql", ["ERD phủ mọi FR", "Ràng buộc thể hiện BR-01, BR-08, BR-12"],
            ["2.4", "3.3"], "Bảng danh sách bảng mục 5.2"),
    "3.5": ("Đặc tả hợp đồng API giữa FE và BE.",
            ["Viết OpenAPI cho 36 endpoint /api/v1", "Định nghĩa DTO request/response",
             "Chuẩn hóa mã lỗi 400/401/403/404/409 và format lỗi"],
            "openapi.yaml", ["Mỗi FR có endpoint tương ứng", "Swagger UI hiển thị được"], ["3.4"], "Bảng API mục 5.3"),
    "3.6": ("Kiểm tra thiết kế đáp ứng đủ yêu cầu.",
            ["Đối chiếu từng FR/BR với màn hình và API", "Ghi thiếu sót và yêu cầu sửa"],
            "Biên bản rà soát thiết kế", ["0 FR bị thiếu thiết kế"], ["3.2", "3.5"], "RTM"),
    "3.7": ("Đóng băng baseline thiết kế.",
            ["Rà soát chéo UI, ERD, API", "Ký duyệt Design Baseline, gắn tag docs v0.1"],
            "Design Baseline được duyệt", ["Mọi thay đổi sau đó phải qua CR"], ["3.6"], "Mốc M1"),
    # ---------------------------------------------------------------- 4 infra
    "4.1": ("Chuẩn bị quản lý mã nguồn.",
            ["Tạo repo GitHub, nhánh main và develop", "Bật branch protection: bắt buộc PR, CI xanh",
             "Viết CONTRIBUTING: Git Flow, quy ước tên nhánh feature/IM-xx"],
            "Repo GitHub", ["Không push thẳng được vào main"], [], "Mục 6.9 báo cáo"),
    "4.2": ("Liên kết code với work item Jira.",
            ["Cài app GitHub for Jira, kết nối repo", "Quy ước commit \"IM-12: ...\""],
            "Jira hiển thị commit/PR trong work item", ["Commit thử có mã IM-xx hiện trong Jira"], ["4.1"], "Mục 6.9"),
    "4.3": ("Đóng gói môi trường chạy.",
            ["Viết docker-compose.yml: mysql:8, backend, frontend, phpmyadmin", "Dùng named volume cho MySQL, file .env.example"],
            "docker-compose.yml", ["docker compose up khởi động đủ 4 service"], ["4.1"], "NFR-10"),
    "4.4": ("Khởi tạo dự án backend.",
            ["Tạo Spring Boot 3 (Web, Security, JPA, Validation, Flyway, MySQL)", "Tạo package theo module",
             "Viết Flyway V1 tạo 12 bảng"],
            "Backend skeleton chạy được", ["App start, Flyway tạo đủ bảng", "Endpoint /actuator/health trả UP"],
            ["3.4", "4.3"], "Mục 5.5 báo cáo"),
    "4.5": ("Khởi tạo dự án frontend.",
            ["Tạo React + Vite + Tailwind", "Cấu hình React Router, layout theo role",
             "Axios interceptor gắn JWT, xử lý 401/403 tập trung"],
            "Frontend skeleton chạy được", ["npm run dev chạy, có layout và trang 404/403"], ["3.2"], "Mục 5.5"),
    "4.6": ("Tự động kiểm tra mỗi Pull Request.",
            ["Viết .github/workflows/ci.yml: build + test backend, build + lint frontend", "Bắt buộc CI xanh trước khi merge"],
            "Workflow CI", ["PR thử chạy CI xanh", "PR lỗi test bị chặn merge"], ["4.4", "4.5"], "NFR-09"),
    # ---------------------------------------------------------------- 5 Sprint 1
    "5.1": ("Đảm bảo Story Sprint 1 sẵn sàng phát triển.",
            ["Rà AC US-01..US-04", "Lập ma trận quyền 3 role x chức năng"], "AC chốt + ma trận quyền",
            ["4 Story đạt Definition of Ready"], ["2.7"], "US-01..US-04, FR-01..FR-06"),
    "5.2": ("Cho phép người dùng đăng nhập và nhận JWT.",
            ["Tạo AuthController: POST /auth/login, /auth/logout, GET /auth/me", "Mật khẩu băm BCrypt, JWT hạn 8 giờ",
             "Sai mật khẩu trả 401, tài khoản khóa trả 403 kèm thông điệp", "Unit test AuthService"],
            "API xác thực + unit test", ["TC-AUTH-01..04 đạt trên Postman", "Swagger cập nhật"],
            ["5.1", "4.4", "3.5"], "FR-01, FR-02, NFR-02, BR tài khoản khóa"),
    "5.3": ("Giao diện đăng nhập.",
            ["Dựng UI-01 theo wireframe, validate email/mật khẩu", "Lưu token, redirect dashboard theo role",
             "Hiển thị lỗi từ API"],
            "Màn hình Login", ["Đăng nhập đủ 3 role chuyển đúng dashboard", "AC1-AC3 của US-01 đạt"],
            ["5.2", "4.5"], "UI-01, FR-01"),
    "5.4": ("Bảo vệ API theo role.",
            ["JwtAuthenticationFilter đọc token", "@PreAuthorize trên từng endpoint theo ma trận quyền",
             "Trả JSON lỗi 401/403 thống nhất"],
            "Cấu hình Spring Security", ["TC-RBAC-02 đạt: Mentor gọi /users bị 403", "Endpoint public chỉ còn login và applications"],
            ["5.2", "5.1"], "FR-04, NFR-02, NFR-03"),
    "5.5": ("Phân quyền phía giao diện.",
            ["ProtectedRoute theo role", "Ẩn menu không thuộc role", "Trang 403 Access Denied"],
            "Route guard + menu theo role", ["TC-RBAC-01, TC-RBAC-03, TC-SEC-01 đạt"], ["5.4", "5.3"], "FR-04"),
    "5.6": ("Quản lý tài khoản.",
            ["API CRUD /users có phân trang", "PATCH /users/{id}/lock khóa/mở", "PUT /auth/password kiểm tra mật khẩu cũ và quy tắc"],
            "API quản lý tài khoản", ["TC-USR-01, TC-USR-02 đạt", "Email trùng trả 409"], ["5.4"], "FR-03, FR-05"),
    "5.7": ("Quản lý phòng ban.",
            ["API CRUD /departments", "Chặn xóa phòng ban còn Intern ACTIVE (trả 409 kèm lý do)"],
            "API phòng ban", ["TC-DEP-01 đạt"], ["5.4"], "FR-06"),
    "5.8": ("Giao diện quản trị.",
            ["UI-10 danh sách/tạo/sửa/khóa tài khoản", "UI-11 danh sách/thêm/sửa/xóa phòng ban", "Hộp thoại xác nhận khi khóa/xóa"],
            "Màn hình UI-10, UI-11", ["AC US-03, US-04 đạt trên giao diện"], ["5.6", "5.7"], "FR-05, FR-06"),
    "5.9": ("Dữ liệu mẫu phục vụ phát triển và kiểm thử.",
            ["Flyway migration seed: 1 Admin, 3 phòng ban, 3 Mentor, 10 Intern", "Ghi tài khoản test vào README"],
            "Migration seed", ["Đăng nhập được bằng tài khoản seed của 3 role"], ["5.6", "5.7"], "Test data"),
    "5.10": ("Nghiệm thu nội bộ trước khi chuyển kiểm thử.",
             ["Chạy từng AC của US-01..US-04 trên giao diện", "Ghi Story đạt/không đạt"],
             "Biên bản nghiệm thu Sprint 1", ["Story không đạt được trả lại kèm lý do"], ["5.8", "5.5"], "US-01..US-04"),
    "5.11": ("Kiểm thử chức năng Sprint 1.",
             ["Chạy 10 test case AUTH/RBAC/USR/DEP", "Ghi Bug trên Jira nếu lỗi", "Lưu ảnh evidence"],
             "Kết quả test Sprint 1", ["100% Critical/High đạt hoặc có bug đã ghi"], ["5.10", "5.9", "9.2"],
             "TC-AUTH-01..04, TC-RBAC-01..03, TC-USR-01..02, TC-DEP-01"),
    "5.12": ("Chuẩn bị backlog cho Sprint 2.",
             ["Làm rõ AC US-05..US-08", "Cập nhật RTM, ước lượng lại nếu cần"], "Backlog Sprint 2 sẵn sàng",
             ["US-05..US-08 đạt Definition of Ready"], ["5.10"], "US-05..US-08"),
    # ---------------------------------------------------------------- 6 Sprint 2
    "6.1": ("Đảm bảo Story Sprint 2 sẵn sàng.",
            ["Rà AC US-05..US-08", "Chốt BR-01..BR-05 kèm ví dụ"], "AC + BR chốt", ["4 Story đạt DoR"],
            ["5.12"], "US-05..US-08, BR-01..BR-05"),
    "6.2": ("Nhận đơn đăng ký thực tập.",
            ["POST /applications (public) nhận multipart: thông tin + CV", "Chỉ nhận PDF <= 5 MB, lưu file ngoài web root",
             "Chặn email đã có đơn PENDING"],
            "API đăng ký", ["TC-REG-01..03 đạt"], ["6.1", "5.4"], "FR-07, BR-01, BR-02"),
    "6.3": ("Form đăng ký thực tập.",
            ["Dựng UI-02 (không cần đăng nhập)", "Validate phía client, upload CV có thanh tiến trình", "Thông báo gửi thành công"],
            "Màn hình UI-02", ["AC US-05 đạt"], ["6.2"], "UI-02, FR-07"),
    "6.4": ("Duyệt hồ sơ và tạo tài khoản Intern.",
            ["POST /applications/{id}/approve: tạo users + interns trong 1 transaction", "Gửi email tài khoản (Spring Mail)",
             "POST /reject bắt buộc lý do"],
            "API duyệt/từ chối", ["TC-APR-01, TC-APR-02 đạt", "Đơn đã xử lý không duyệt lại được"],
            ["6.2"], "FR-08, FR-09, BR-03"),
    "6.5": ("Giao diện duyệt hồ sơ.",
            ["UI-03 danh sách đơn lọc theo trạng thái", "Xem CV, nút Duyệt/Từ chối có hộp thoại nhập lý do"],
            "Màn hình UI-03", ["AC US-06 đạt"], ["6.4", "6.3"], "UI-03, FR-08"),
    "6.6": ("Quản lý hồ sơ Intern.",
            ["GET /interns có tìm kiếm, lọc phòng ban/trạng thái, phân trang", "GET/PUT /interns/{id}",
             "PATCH /interns/{id}/department"],
            "API Intern", ["TC-INT-01..03 đạt", "Mentor chỉ thấy Intern của mình"], ["6.4"], "FR-10..FR-12"),
    "6.7": ("Giao diện Intern.",
            ["UI-04 bảng danh sách + bộ lọc", "UI-05 chi tiết hồ sơ, sửa thông tin, phân phòng ban"],
            "Màn hình UI-04, UI-05", ["AC US-07 đạt"], ["6.6"], "UI-04, UI-05"),
    "6.8": ("Phân công Mentor.",
            ["GET /mentors, GET /mentors/me/interns", "PATCH /interns/{id}/mentor kiểm tra BR-04 (tối đa 5) và BR-05 (cùng phòng ban)"],
            "API Mentor", ["TC-MEN-01, TC-MEN-02 đạt"], ["6.6"], "FR-13..FR-15, BR-04, BR-05"),
    "6.9": ("Giao diện Mentor.",
            ["UI-06 danh sách Mentor kèm số Intern đang hướng dẫn", "Hộp thoại phân công, hiển thị lỗi BR-04/BR-05"],
            "Màn hình UI-06", ["AC US-08 đạt"], ["6.8", "6.7"], "UI-06"),
    "6.10": ("Nghiệm thu nội bộ Sprint 2.", ["Chạy từng AC US-05..US-08"], "Biên bản nghiệm thu Sprint 2",
             ["Story không đạt được trả lại kèm lý do"], ["6.9", "6.5"], "US-05..US-08"),
    "6.11": ("Kiểm thử chức năng Sprint 2.", ["Chạy 10 test case REG/APR/INT/MEN", "Ghi Bug, lưu evidence",
                                               "Chạy lại Newman hồi quy Sprint 1"],
             "Kết quả test Sprint 2", ["100% Critical/High đạt hoặc có bug đã ghi"], ["6.10"],
             "TC-REG, TC-APR, TC-INT, TC-MEN"),
    "6.12": ("Chuẩn bị backlog Sprint 3.", ["Làm rõ AC US-09..US-12", "Cập nhật RTM"], "Backlog Sprint 3 sẵn sàng",
             ["US-09..US-12 đạt DoR"], ["6.10"], "US-09..US-12"),
    # ---------------------------------------------------------------- 7 Sprint 3
    "7.1": ("Đảm bảo Story Sprint 3 sẵn sàng.",
            ["Rà AC US-09..US-12", "Chốt vòng đời Task và BR-06..BR-10 (giờ đi muộn 8:30, hạn báo cáo)"],
            "AC + State Diagram Task", ["4 Story đạt DoR"], ["6.12"], "US-09..US-12, BR-06..BR-10"),
    "7.2": ("Mentor giao task.",
            ["POST /tasks kiểm tra Mentor phụ trách (BR-06), deadline tương lai", "GET /tasks?internId=",
             "Tạo notification cho Intern"],
            "API giao task", ["TC-TASK-01..03 đạt"], ["7.1", "6.8"], "FR-16, FR-30, BR-06"),
    "7.3": ("Giao diện giao task.",
            ["UI-07 Task Board theo Intern, cột theo trạng thái", "Form tạo task: tiêu đề, mô tả, ưu tiên, deadline"],
            "Màn hình UI-07", ["AC US-09 đạt"], ["7.2"], "UI-07"),
    "7.4": ("Intern cập nhật task.",
            ["GET /tasks/my-tasks", "PUT /tasks/{id}/status theo vòng đời, chỉ Mentor chuyển DONE (BR-07)",
             "GET/POST /tasks/{id}/comments"],
            "API cập nhật task + bình luận", ["TC-TASK-04, TC-TASK-05 đạt"], ["7.2"], "FR-17..FR-19, BR-07"),
    "7.5": ("Giao diện task của Intern.",
            ["UI-08 danh sách task, sắp theo deadline", "Task Detail: đổi trạng thái, khung bình luận"],
            "Màn hình UI-08", ["AC US-10 đạt"], ["7.4", "7.3"], "UI-08"),
    "7.6": ("Chấm công.",
            ["POST /attendances/check-in, /check-out", "UNIQUE(intern, ngày) chặn chấm 2 lần (BR-08), đánh dấu muộn sau 8:30",
             "GET /attendances?month= tổng hợp công"],
            "API chấm công", ["TC-ATT-01..03 đạt"], ["6.6"], "FR-20, FR-21, BR-08, BR-09"),
    "7.7": ("Giao diện chấm công.",
            ["Nút Check-in/Check-out trên dashboard Intern", "Bảng công tháng cho Mentor, Admin"],
            "Chức năng chấm công trên UI", ["AC US-11 đạt"], ["7.6"], "FR-20, FR-21"),
    "7.8": ("Báo cáo tuần.",
            ["POST /reports, gắn cờ LATE sau Chủ nhật 23:59 (BR-10)", "GET /reports?internId=",
             "POST /reports/{id}/feedback cho Mentor"],
            "API báo cáo tuần", ["TC-RPT-01..03 đạt"], ["7.4"], "FR-22, FR-23, BR-10"),
    "7.9": ("Giao diện báo cáo tuần.",
            ["UI-09 form nộp báo cáo: việc đã làm, kế hoạch tuần sau", "Danh sách báo cáo + phản hồi cho Mentor"],
            "Màn hình UI-09", ["AC US-12 đạt"], ["7.8"], "UI-09"),
    "7.10": ("Nghiệm thu nội bộ Sprint 3.", ["Chạy từng AC US-09..US-12"], "Biên bản nghiệm thu Sprint 3",
             ["Story không đạt được trả lại kèm lý do"], ["7.9", "7.7", "7.5"], "US-09..US-12"),
    "7.11": ("Kiểm thử chức năng Sprint 3.", ["Chạy 11 test case TASK/ATT/RPT", "Ghi Bug, lưu evidence",
                                                "Hồi quy Newman Sprint 1-2"],
             "Kết quả test Sprint 3", ["100% Critical/High đạt hoặc có bug đã ghi"], ["7.10"], "TC-TASK, TC-ATT, TC-RPT"),
    "7.12": ("Chuẩn bị backlog Sprint 4.", ["Làm rõ AC US-13..US-16", "Cập nhật RTM"], "Backlog Sprint 4 sẵn sàng",
             ["US-13..US-16 đạt DoR"], ["7.10"], "US-13..US-16"),
    # ---------------------------------------------------------------- 8 Sprint 4
    "8.1": ("Chốt tiêu chí đánh giá và công thức số liệu.",
            ["5 tiêu chí thang 10, cách xếp loại BR-13", "Công thức tiến độ BR-11 kèm ví dụ tính tay",
             "Danh sách chỉ số từng dashboard"],
            "Tài liệu tiêu chí + công thức", ["Có 2 ví dụ tính tay để làm test oracle"], ["7.12"], "BR-11..BR-15"),
    "8.2": ("Mentor đánh giá Intern.",
            ["POST /evaluations: MIDTERM/FINAL, điểm 0..10, tính tổng và xếp loại", "UNIQUE(intern, type) theo BR-12",
             "GET /evaluations?internId="],
            "API đánh giá", ["TC-EVA-01..03 đạt"], ["8.1", "6.8"], "FR-24, FR-25, BR-12, BR-13"),
    "8.3": ("Giao diện đánh giá.",
            ["UI-12 form 5 tiêu chí + nhận xét cho Mentor", "Trang xem kết quả cho Intern"],
            "Màn hình UI-12", ["AC US-13 đạt"], ["8.2"], "UI-12"),
    "8.4": ("Tính tiến độ thực tập.",
            ["ProgressService: 50% task DONE + 25% báo cáo đúng hạn + 25% chuyên cần", "GET /interns/{id}/progress",
             "Unit test với 2 ví dụ tính tay"],
            "API tiến độ", ["TC-PRG-01 đạt, kết quả khớp ví dụ tính tay"], ["7.4", "7.6", "7.8"], "FR-26, BR-11"),
    "8.5": ("Hiển thị tiến độ.",
            ["Thanh tiến độ trên UI-05 và dashboard Intern", "Đánh dấu cảnh báo khi < 50% sau nửa kỳ"],
            "Component thanh tiến độ", ["AC US-14 đạt"], ["8.4"], "FR-26"),
    "8.6": ("Số liệu dashboard.",
            ["GET /dashboard/admin: Intern theo trạng thái/phòng ban, task quá hạn",
             "GET /dashboard/mentor, /dashboard/intern", "Truy vấn tổng hợp có index, < 1 giây"],
            "API dashboard", ["TC-DSH-01, TC-DSH-02 đạt", "Đáp ứng NFR-01"], ["8.4"], "FR-27, NFR-01"),
    "8.7": ("Giao diện dashboard.",
            ["3 biến thể dashboard theo role", "Biểu đồ Recharts: cột, tròn, thẻ KPI"],
            "Màn hình UI-13", ["AC US-15 đạt", "Số liệu khớp API"], ["8.6"], "UI-13"),
    "8.8": ("Xuất kết quả và kết thúc kỳ.",
            ["GET /results/export?format=xlsx|pdf (Apache POI, OpenPDF)", "POST /interns/{id}/complete kiểm tra BR-14",
             "Khóa sửa dữ liệu Intern COMPLETED (BR-15)"],
            "API xuất file + kết thúc kỳ", ["TC-EXP-01, TC-EXP-02 đạt"], ["8.2"], "FR-28, FR-29, BR-14, BR-15"),
    "8.9": ("Giao diện xuất file và kết thúc kỳ.",
            ["Nút xuất Excel/PDF trên UI-04", "Nút Kết thúc kỳ có hộp thoại xác nhận"],
            "Chức năng trên UI Admin", ["AC US-16 đạt"], ["8.8"], "FR-28, FR-29"),
    "8.10": ("Kiểm tra độ đúng số liệu.",
             ["Đối chiếu dashboard với truy vấn SQL tay", "Đối chiếu file Excel/PDF với dữ liệu"],
             "Biên bản đối chiếu số liệu", ["Sai lệch = 0"], ["8.7", "8.9"], "BR-11..BR-15"),
    "8.11": ("Kiểm thử chức năng Sprint 4.", ["Chạy 8 test case EVA/PRG/DSH/EXP", "Ghi Bug, lưu evidence",
                                                "Hồi quy Newman Sprint 1-3"],
             "Kết quả test Sprint 4", ["100% Critical/High đạt hoặc có bug đã ghi"], ["8.10"], "TC-EVA, TC-PRG, TC-DSH, TC-EXP"),
    "8.12": ("Chuẩn bị UAT.",
             ["Viết 8 kịch bản UAT-01..UAT-08 theo luồng nghiệp vụ", "Chuẩn bị dữ liệu và tài khoản UAT"],
             "Bộ kịch bản UAT", ["Mỗi kịch bản có bước, dữ liệu, kết quả mong đợi"], ["8.10"], "Bảng UAT chương 8"),
    # ---------------------------------------------------------------- 9 QA
    "9.1": ("Lập kế hoạch kiểm thử.",
            ["Xác định phạm vi, cấp độ, công cụ, môi trường", "Định nghĩa severity S1..S4, tiêu chí vào/ra"],
            "Test Plan", ["Được PM duyệt trước Sprint 1 kết thúc"], ["2.7"], "Chương 8 báo cáo"),
    "9.2": ("Viết test case từ AC trước khi code xong.",
            ["Viết 40 test case: bước, dữ liệu, kết quả mong đợi", "Gắn mỗi test case với Story trong RTM",
             "Chuẩn bị dataset"],
            "Bộ test case (Excel)", ["Mỗi AC có ít nhất 1 test case"], ["9.1"], "TEST_CASES, RTM"),
    "9.3": ("Tự động hóa kiểm thử API.",
            ["Tạo Postman collection theo module, dùng biến môi trường và token", "Chạy bằng Newman từ dòng lệnh"],
            "Postman collection + lệnh Newman", ["newman run chạy hết không lỗi cấu hình"], ["9.2", "5.2"], "tests/postman"),
    "9.4": ("Kiểm thử liên tục theo Story.",
            ["Khi Story vào cột In Testing: chạy test case liên quan", "Đạt: chuyển Done; lỗi: tạo Bug, trả về In Progress"],
            "Kết quả test cập nhật trên Jira", ["Không Story nào Done khi chưa chạy test"], ["9.2"], "Mọi TC"),
    "9.5": ("Quản lý bug.",
            ["Ghi Bug: môi trường, bước tái hiện, kết quả mong đợi/thực tế, ảnh", "Gán Priority theo severity, link tới Story",
             "Verify bản sửa, đóng hoặc Reopen"],
            "Bug trên Jira", ["Mỗi bug có đủ thông tin tái hiện", "Bug S1 sửa trong ngày"], ["9.1"], "Mục severity chương 8"),
    "9.6": ("Tự động hóa kiểm thử giao diện.",
            ["Selenium WebDriver cho 5 luồng: đăng nhập, duyệt hồ sơ, giao task, nộp báo cáo, đánh giá",
             "Page Object Model, chạy headless"],
            "Bộ test Selenium", ["5 kịch bản chạy xanh trên môi trường TEST"], ["8.7"], "tests/selenium"),
    "9.7": ("Hồi quy toàn hệ thống trước phát hành.",
            ["Chạy Newman toàn bộ + Selenium 5 luồng", "Chạy tay test case Critical/High còn lại", "Lập Test Report"],
            "Test Report hồi quy", ["100% Critical/High đạt, 0 bug S1/S2 mở"], ["9.6", "10.1", "10.2"], "Tiêu chí kết thúc"),
    # ---------------------------------------------------------------- 10 Sprint 5
    "10.1": ("Sửa dứt điểm bug backend nghiêm trọng.",
             ["Lọc Bug S1/S2 phần backend trên Jira", "Sửa kèm unit test tái hiện lỗi", "Chuyển In Testing để TEST verify"],
             "Bản sửa backend", ["0 bug S1/S2 backend mở"], ["9.5"], "Bug trên Jira"),
    "10.2": ("Sửa dứt điểm bug frontend nghiêm trọng.",
             ["Lọc Bug S1/S2 phần frontend", "Sửa và kiểm tra trên 3 trình duyệt (NFR-05)"],
             "Bản sửa frontend", ["0 bug S1/S2 frontend mở"], ["9.5"], "NFR-05"),
    "10.3": ("Tối ưu hiệu năng và bảo mật cơ bản.",
             ["Bật log truy vấn chậm, thêm index/sửa N+1", "Rà OWASP Top 10: injection, broken access control, lộ dữ liệu"],
             "Danh sách vấn đề đã xử lý", ["API chính < 1 giây (NFR-01)", "Không còn lỗi truy cập dữ liệu người khác"],
             ["10.1"], "NFR-01, NFR-02, NFR-03"),
    "10.4": ("Chuẩn bị bản phát hành.",
             ["Tạo nhánh release/1.0.0 từ develop", "Chạy Flyway trên bản sao DB", "Merge vào main, gắn tag v1.0.0"],
             "Tag v1.0.0", ["Build từ tag chạy được sạch"], ["10.3", "9.7"], "Mục 6.9 báo cáo"),
    "10.5": ("Dựng môi trường UAT.",
             ["Deploy bằng Docker Compose trên máy UAT", "Nạp dữ liệu gần thực tế, tạo tài khoản UAT"],
             "Môi trường UAT", ["Người dùng UAT đăng nhập được"], ["10.4"], "NFR-04"),
    "10.6": ("Tổ chức kiểm thử chấp nhận.",
             ["Hướng dẫn người dùng đại diện (bạn cùng lớp)", "Chạy 8 kịch bản UAT-01..UAT-08"],
             "Kết quả UAT", ["8/8 kịch bản được chạy"], ["10.5", "8.12"], "UAT-01..UAT-08"),
    "10.7": ("Ghi nhận lỗi UAT.",
             ["Ghi lỗi UAT lên Jira theo severity", "Verify bản sửa trong tuần 12"],
             "Danh sách lỗi UAT", ["Không còn lỗi S1/S2 từ UAT"], ["10.6"], "Bug trên Jira"),
    "10.8": ("Chấp nhận sản phẩm.",
             ["Tổng hợp phản hồi UAT, cập nhật RTM", "Lập và ký biên bản UAT Sign-off"],
             "Biên bản UAT Sign-off", ["Có xác nhận của người dùng đại diện"], ["10.7"], "SC-05"),
    "10.9": ("Tài liệu kỹ thuật phát hành.",
             ["Release Notes v1.0.0", "Deployment Guide từng bước", "Cập nhật Swagger, README"],
             "Bộ tài liệu kỹ thuật", ["Người khác cài được theo Deployment Guide"], ["10.4"], "SC-06"),
    "10.10": ("Tài liệu người dùng.",
              ["User Manual cho Admin, Mentor, Intern kèm ảnh màn hình", "Mục câu hỏi thường gặp"],
              "User Manual", ["Mỗi FR có hướng dẫn thao tác"], ["10.4"], "SC-06"),
    "10.11": ("Sao lưu và đóng gói bàn giao.",
              ["mysqldump database", "Đóng gói mã nguồn từ tag v1.0.0", "Kiểm tra khôi phục trong 30 phút"],
              "File backup + gói mã nguồn", ["Khôi phục thử thành công (NFR-10)"], ["10.4"], "NFR-10"),
    "10.12": ("Nghiệm thu với giảng viên.",
              ["Chuẩn bị slide và kịch bản demo 15 phút", "Demo luồng chính, trình bày evidence Jira/GitHub",
               "So sánh baseline và thực tế (lịch, chi phí, phạm vi)"],
              "Buổi nghiệm thu", ["Demo chạy trọn luồng không lỗi", "Nộp đủ hồ sơ"], ["10.8", "10.9", "10.10", "1.10"],
              "Mốc M6"),
}

MILESTONE_DETAILS = {
    "11.1": "Scope, SRS, Use Case, User Story, UI/ERD/API đã duyệt; Design Baseline ký.",
    "11.2": "US-01..US-04 Done (13 SP), test Sprint 1 đạt.",
    "11.3": "US-05..US-08 Done (14 SP), test Sprint 2 đạt.",
    "11.4": "US-09..US-12 Done (16 SP), test Sprint 3 đạt.",
    "11.5": "US-13..US-16 Done (16 SP), đủ 30 FR, kịch bản UAT sẵn sàng.",
    "11.6": "UAT Sign-off, tag v1.0.0, nghiệm thu thành công.",
}
